FROM amazoncorretto:17-alpine3.18
WORKDIR /app
COPY target/com.service2-3.1.5-shaded.jar app.jar
EXPOSE 8080
#HEALTHCHECK --interval=30s --timeout=3s \
#  CMD curl -f http://localhost:8080/actuator/health || exit 1
ENTRYPOINT ["java", "-jar", "app.jar"]